trigger: none  # we only trigger on PRs

pr:
  branches:
    include:
    - master
  paths:
    include:
    - mono/*
    - msvc/mono.vcxproj
    - autogen.sh
    - configure.ac
    - Makefile.am
    - acinclude.m4
    - config.rpath
    - winconfig.h

pool:
  vmImage: ubuntu-latest

variables:
- name: skipComponentGovernanceDetection
  value: true

resources:
  repositories:
  - repository: RuntimeRepo
    type: github
    endpoint: MyFirstProject
    name: akoeplinger/repo-sync-test-runtime

steps:

- checkout: RuntimeRepo

- bash: |
    echo hello
    ls -la
  displayName: Apply to target repo
